version: "3"
services:
  server:
    build: .
    depends_on:
      - database
    ports:
      - 3000:3000
#    networks:
#      - adminer-to-mysql
    links:
      - database
    volumes:
      - .:/usr/src/app
    restart: always

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - adminer-to-mysql


  database:
    container_name: BDFAETERJ
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - adminer-to-mysql
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./data/db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "faeterj"
      MYSQL_USER: "root"

networks:
  adminer-to-mysql:
    driver: bridge
